/** Stable codes used at the Provider boundary and in machine diagnostics. */
export const MODEL_DISCOVERY_FAILED_CODE = 'MODEL_DISCOVERY_FAILED' as const
export const MODEL_DISCOVERY_EMPTY_CODE = 'MODEL_DISCOVERY_EMPTY' as const
export const MODEL_DISCOVERY_TIMEOUT_CODE = 'MODEL_DISCOVERY_TIMEOUT' as const
export const MODEL_DISCOVERY_OUTPUT_LIMIT_CODE = 'MODEL_DISCOVERY_OUTPUT_LIMIT' as const
export const UNSUPPORTED_REASONING_EFFORT_CODE = 'UNSUPPORTED_REASONING_EFFORT' as const
export const UNSUPPORTED_TOOLS_CODE = 'UNSUPPORTED_TOOLS' as const
export const AGY_INTERNAL_TOOL_EVENT_CODE = 'AGY_INTERNAL_TOOL_EVENT' as const
export const PERMISSION_REQUIRED_CODE = 'PERMISSION_REQUIRED' as const
export const DSH_CONTEXT_UNAVAILABLE_CODE = 'DSH_CONTEXT_UNAVAILABLE' as const
export const DSH_SESSION_REQUIRED_CODE = 'DSH_SESSION_REQUIRED' as const
export const DSH_SESSION_UNAVAILABLE_CODE = 'DSH_SESSION_UNAVAILABLE' as const
export const DSH_SESSION_UNKNOWN_CODE = 'DSH_SESSION_UNKNOWN' as const
export const DSH_SESSION_INVALID_CODE = 'DSH_SESSION_INVALID' as const
export const DSH_WORKSPACE_UNAVAILABLE_CODE = 'DSH_WORKSPACE_UNAVAILABLE' as const
export const DSH_WORKSPACE_MISMATCH_CODE = 'DSH_WORKSPACE_MISMATCH' as const
export const DSH_SANDBOX_UNAVAILABLE_CODE = 'DSH_SANDBOX_UNAVAILABLE' as const
export const DSH_PERMISSION_UNAVAILABLE_CODE = 'DSH_PERMISSION_UNAVAILABLE' as const
export const DSH_APPROVAL_UNAVAILABLE_CODE = 'DSH_APPROVAL_UNAVAILABLE' as const

export type ModelDiscoveryErrorCode =
  | typeof MODEL_DISCOVERY_FAILED_CODE
  | typeof MODEL_DISCOVERY_EMPTY_CODE
  | typeof MODEL_DISCOVERY_TIMEOUT_CODE
  | typeof MODEL_DISCOVERY_OUTPUT_LIMIT_CODE

const MODEL_DISCOVERY_ERROR_CODES: readonly ModelDiscoveryErrorCode[] = [
  MODEL_DISCOVERY_FAILED_CODE,
  MODEL_DISCOVERY_EMPTY_CODE,
  MODEL_DISCOVERY_TIMEOUT_CODE,
  MODEL_DISCOVERY_OUTPUT_LIMIT_CODE,
]

export function isModelDiscoveryErrorCode(value: unknown): value is ModelDiscoveryErrorCode {
  return typeof value === 'string' && MODEL_DISCOVERY_ERROR_CODES.includes(value as ModelDiscoveryErrorCode)
}
